[package]
name = "libquassel"
version = "0.1.0"
authors = ["Max Audron <audron@cocaine.farm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
bytes = "0.5"
byteorder = "1.3.2"
flate2 = { version = "1.0", features = ["tokio"], optional = true }
tokio = { version = "0.2", features = ["full"], optional = true }
tokio-util = { version = "0.2", features = ["codec"], optional = true }
failure = "0.1"
futures-util = { version = "0.3", features = ["std"] }
futures = "0.3"

[features]
framing = ["tokio", "tokio-util", "flate2"]
client = ["tokio", "tokio-util", "framing", "futures-util"]

default = []
