[package]
name = "libquassel"
version = "0.1.0"
authors = ["Max Audron <audron@cocaine.farm>"]
edition = "2018"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
byteorder = "1.3.2"
failure = "0.1"

bytes = { version = "0.5", optional = true }
flate2 = { version = "1.0", features = ["tokio"], optional = true }
tokio = { version = "0.2", features = ["full"], optional = true }
tokio-util = { version = "0.2", features = ["codec"], optional = true }
futures-util = { version = "0.3", features = ["std"], optional = true }
futures = { version = "0.3", optional = true }

[features]
framing = ["tokio", "tokio-util", "flate2", "bytes"]
client = ["tokio", "tokio-util", "futures", "futures-util", "framing"]

default = []

[[bin]]
name = "quassel-client"
required-features = ["client"]
